Repository UBC-MDS/netviz, pull requests merged in 2022-03, with the labels that each got.

#27 Added os for directory path
  src/app.py
Labels: enhancement

#26 Add requirements.txt and move proposal.md to doc
  doc/proposal.md
  requirements.txt
Labels: enhancement

#29 README.md improvement
  README.md
Labels: documentation

#30 Add GIF of demo
  README.md
Labels: documentation

#31 Add reflection
  doc/reflection-milestone2.md
Labels: documentation

#42 Add app title and favicon
  app.py
  assets/favicon.ico
Labels: enhancement

#43 Change the assets folder
  src/assets/netviz.ico
Labels: bug

#44 Change favicon name
  src/assets/favicon.ico
Labels: bug

#50 Netviz App Improvement
  README.md
  src/app.py
Labels: enhancement
